export const REQUESTTABLELISTEND = 'REQUEST_TABLE_LIST_END';
export const REQUESTTABLELISTSTART = 'REQUEST_TABLE_LIST_START';

export const REQUESTPOSITIONLISTSTART = 'REQUEST_POSITION_LIST_START';
export const REQUESTPOSITIONLISTEND = 'REQUEST_POSITION_LIST_END';

export const FORMCHANGE = 'FORM_CHANGE';
